nix: boost 1.81 C++17 detection seems to be broken on Clang 16
std::{unary,binary}_function is removed in C++17, but boost still
tries to use it:

  vectorscan> In file included from include/boost/multi_array/multi_array_ref.hpp:32:
  868
  vectorscan> include/boost/functional.hpp:45:24: error: no member named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
  869
  vectorscan>             using std::unary_function;
  870
  vectorscan>                   ~~~~~^